config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :stocks, only: [:index, :show, :get_stock]
  devise_for :users
  # , controllers: { registrations: "registrations" }
  # get 'home/index'
  root 'home#index'
  get '/dashboard' => 'dashboard#dashboard', as: 'dashboard' 
  get '/panel' => 'panel#panel', as: 'panel' 
  resources :users
  get '/history' => 'history#history', as: 'history'
  get '/portfolio' => 'portfolio#portfolio', as: 'portfolio' do
    post :sell_stock
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/stock.rb
class Stock < ApplicationRecord
    has_and_belongs_to_many :users

    has_many :transactions

    def self.client
        client = IEX::Api::Client.new(
            publishable_token: 'pk_d7c9543c74524df2b712630b34f2cdb6',
            secret_token: 'sk_bae1c522e90d4da6aae8437a2509a173',
            endpoint: 'https://cloud.iexapis.com/v1'
        )
        return client
    end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_stock, only: %i[ show edit update destroy ]
  # actions :all, except [:index, :show, :get_stock]

  # GET /stocks or /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1 or /stocks/1.json
  def show
    @stock = Stock.find(params[:id])
  end

  # def get_stock
  #   @client = Stock.client
  # end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks or /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
      @stock.destroy

    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:company_code, :company_name, :latest_price, :change, :change_percent, :change_percent_s)
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb
<%= form_with(model: stock) do |form| %>
  <% if stock.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :company_code, style: "display: block" %>
    <%= form.text_field :company_code %>
  </div>

  <div>
    <%= form.label :company_name, style: "display: block" %>
    <%= form.text_field :company_name %>
  </div>

  <div>
    <%= form.label :latest_price, style: "display: block" %>
    <%= form.number_field :latest_price %>
  </div>

  <div>
    <%= form.label :change, style: "display: block" %>
    <%= form.number_field :change %>
  </div>

  <div>
    <%= form.label :change_percent, style: "display: block" %>
    <%= form.number_field :change_percent %>
  </div>

  <div>
    <%= form.label :change_percent_s, style: "display: block" %>
    <%= form.text_field :change_percent_s %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/_stock.html.erb
<div id="<%= dom_id stock %>">
  <p>
    <strong>Company code:</strong>
    <%= stock.company_code %>
  </p>

  <p>
    <strong>Company name:</strong>
    <%= stock.company_name %>
  </p>

  <p>
    <strong>Latest price:</strong>
    <%= stock.latest_price %>
  </p>

  <p>
    <strong>Change:</strong>
    $<%= stock.change %>
  </p>

  <p>
    <strong>Change percent:</strong>
    <%= stock.change_percent %>
  </p>

  <p>
    <strong>Change percent s:</strong>
    <%= stock.change_percent_s %>
  </p>

</div>

app/views/stocks/edit.html.erb
<h1>Editing stock</h1>

<%= render "form", stock: @stock %>

<br>

<div>
  <%= link_to "Show this stock", @stock %> |
  <%= link_to "Back to stocks", stocks_path %>
</div>

app/views/stocks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Stocks</h1>

<%#<%= Stock.client.quote('BBBY').company_name
<%= Stock. %>

<h2>Top 10 Stocks by Market Cap</h2>

<%#<table>
  <thead>
    <tr>
      <th>
    </tr>
  </thead>
</table>%>

<% Stock.all.each do |stock| %>
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= stock.company_code %></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= stock.company_name %></h6>
      <p class="card-text">$<%= stock.latest_price %> | <%= stock.change_percent_s %> </p>
      <%= link_to "View stock", stock_path(stock) %>
      <%= link_to "Trade", "/transactions/new?stock_id=#{stock.id}" %>
    </div>
  </div>
<% end %>



<%# <div id="stocks">
  <% @stocks.each do |stock|
    <%= render stock
    <p>
      <%= link_to "Show this stock", stock
    </p>
  <% end 
</div>

<%= link_to "New stock", new_stock_path %>

app/views/stocks/new.html.erb
<h1>New stock</h1>

<%= render "form", stock: @stock %>

<br>

<div>
  <%= link_to "Back to stocks", stocks_path %>
</div>

app/views/stocks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @stock %>

<div>
  <%= link_to "Back to stocks", stocks_path %>
</div>