config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :stocks, only: [:index, :show, :get_stock]
  devise_for :users
  # , controllers: { registrations: "registrations" }
  # get 'home/index'
  root 'home#index'
  get '/dashboard' => 'dashboard#dashboard', as: 'dashboard' 
  get '/panel' => 'panel#panel', as: 'panel' 
  resources :users
  get '/history' => 'history#history', as: 'history'
  get '/portfolio' => 'portfolio#portfolio', as: 'portfolio' do
    post :sell_stock
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  # has_many :user_roles
  # has_many :roles, through: :user_roles
  has_and_belongs_to_many :stocks

  # after_initialize :set_default_role, 

  after_create :set_default_role, :set_default_approval

  def set_default_role
    self.role = 'trader' if email != 'admin@trader.com'
  end

  def set_default_approval
    self.approved = 'false' unless role == 'admin'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user, only: %i[ show new create edit update destroy ]
    before_action :correct_user

    def index
        @users = User.all
    end

    def show
      @user = User.find(params[:id])
    end

    def new
      @user = User.new
    end

    def edit
      @user = User.find(params[:id])
    end

    def create
        @user = User.new(user_params)

        respond_to do |format|
            if @user.save
              # Tell the UserMailer to send a welcome email after save
              UserMailer.with(user: @user).welcome_email.deliver_later
      
              format.html { redirect_to(@user, notice: 'User was successfully created.') }
              format.json { render json: @user, status: :created, location: @user }
            else
              format.html { render action: 'new' }
              format.json { render json: @user.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
      @user = User.find(params[:id])
      if @user.update(user_params)

        ConfirmationMailer.with(user: @user).confirmation_email.deliver_later

        redirect_to users_path, notice: 'User is now approved'
      end
    end

    private

      def correct_user
        @user = current_user
        redirect_to dashboard_path, notice: 'You are not authorized to view this page' unless @user.role == 'admin'
      end

      def set_user
        @user = User.find(params[:id])
      end

      def user_params
        params.require(:user).permit(:email, :approved)
      end

  end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being approved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :approved, style: "display: block" %>
    <%= form.select :approved, [true, false] %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<h1>TRADER PROFILE</h1>

<div id="<%= dom_id user %>">
  
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Status:</strong>
      <% if user.approved == true %>
        <p>Approved</p>
      <% elsif %>
        <p>Pending Approval</p>
      <% end %>
  </p>

  <%= link_to 'Back to Traders', users_path %>

</div>

app/views/users/edit.html.erb
<h1>Approve User</h1>

<%= render "form", user: @user %>

<br>

<%= link_to "Back to Users", users_path %>

app/views/users/index.html.erb
<h1>TRADERS</h1>
<br />
<br />

<h3>Pending Traders</h3>
<table class="table">
    <thead>
        <tr colspan="6">
            <th>ID</th>
            <th>Email</th>
            <th>Role</th>
            <th>Status</th>
            <th colspan="2"></th>
        </tr>
    </thead>


    <tbody>
        <% @users.each do |user| %>
            <% if user.role == 'trader' && user.approved == false %>
                <tr>
                    <td><%= user.id %></td>
                    <td><%= user.email %></td>
                    <td><%= user.role %></td>
                    <% if user.approved == true %>
                        <td>Approved</td>
                    <% elsif %>
                        <td>Pending Approval</td>
                    <% end %>
                    <td><%= link_to "Approve / Edit Trader", edit_user_path(user) %></td>
                    <td><%= link_to "Show", user_path(user) %></td>
                </tr>
            <% end %>
        <% end %>
    </tbody>
</table>

<br />
<br />
<br />
<br />

<h3>All Traders</h3>
<table class="table">
    <thead>
        <tr colspan="6">
            <th>ID</th>
            <th>Email</th>
            <th>Role</th>
            <th>Status</th>
            <th colspan="2"></th>
        </tr>
    </thead>


    <tbody>
        <% @users.each do |user| %>
            <% if user.role == 'trader' %>
                <tr>
                    <td><%= user.id %></td>
                    <td><%= user.email %></td>
                    <td><%= user.role %></td>
                    <% if user.approved == true %>
                        <td>Approved</td>
                    <% elsif %>
                        <td>Pending Approval</td>
                    <% end %>
                    <td><%= link_to "Edit Trader", edit_user_path(user) %></td>
                    <td><%= link_to "Show", user_path(user) %></td>
                </tr>
            <% end %>
        <% end %>
    </tbody>
</table>

<%= link_to 'Back to Admin Panel', panel_path %>
<br />
<br />

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>