config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :stocks, only: [:index, :show, :get_stock]
  devise_for :users
  # , controllers: { registrations: "registrations" }
  # get 'home/index'
  root 'home#index'
  get '/dashboard' => 'dashboard#dashboard', as: 'dashboard' 
  get '/panel' => 'panel#panel', as: 'panel' 
  resources :users
  get '/history' => 'history#history', as: 'history'
  get '/portfolio' => 'portfolio#portfolio', as: 'portfolio' do
    post :sell_stock
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
<%= link_to 'Trading App', root_path, class:"navbar-brand font-weight-bold text-warning" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <% if user_signed_in? %>
        <% if current_user.role == 'admin' %>
          <li class="nav-item">
            <%= link_to "Panel", panel_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Transactions", transactions_path, class:"nav-link" %>
          </li>
          
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, 'data-turbo-method': :delete, class:"nav-link" %>
          </li>

        <% else %>

          <li class="nav-item">
            <%= link_to 'Dashboard', dashboard_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'My Portfolio', portfolio_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Transaction History", history_path, class:"nav-link" %>
          </li>
          
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, 'data-turbo-method': :delete, class:"nav-link" %>
          </li>
        <% end %>
      <% else %>

        <li class="nav-item">
          <%= link_to 'Register', new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Log in', new_user_session_path, class:"nav-link" %>
        </li>
      <% end %>

      
    </ul>
  </div>
</nav>
        

app/views/home/index.html.erb
<h1>STOCK TRADING APP</h1>

<%# Move this to a navbar partial %> 